---

- hosts: all
  become: true
  vars_files:
    - vars/user.yml
    - vars/sen.yml
  tasks:

  - name: hash pass
    set_fact:
      hashed_password: "{{ password | password_hash('sha512') }}"

  - name: create ansible user called "{{ user }}"
    tags: always
    user:
      name: "{{ user }}" 
      password: "{{ hashed_password }}"

  - name: add ssh key for ansible
    tags: always
    authorized_key:
      user: "{{ user }}" 
      key: "{{ key }}"

  - name: add sudoers file for ansible user
    tags: always
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

