---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    ansible.builtin.dnf:
      update_cache: yes 

  - name: install httpd package
    ansible.builtin.dnf:
      name: httpd
      state: latest

  - name: add php support for httpd
    ansible.builtin.dnf:
      name: php-fpm 
      state: latest
      
