---

- hosts: all
  become: true
  vars_files: 
    - vars/rocky-var.yml
    - vars/ubuntu-var.yml
  tasks:

  - name: install httpd and php packages for Rocky
    ansible.builtin.dnf:
      name: 
        - "{{ httpd_package }}" 
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apache2 and php packages for Ubuntu
    ansible.builtin.apt:
      name: 
        - "{{ apache_package }}" 
        - "{{ lib_php_package }}" 
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
                                           
