---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Rocky)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  vars_files:
    - vars/ubuntu-var.yml
    - vars/rocky-var.yml
  tasks:

  - name: install httpd and php packages for Rocky
    ansible.builtin.dnf:
      name: 
        - "{{ httpd_package }}" 
        - "{{ php_package }}"
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install apache2 and php packages for Ubuntu
    ansible.builtin.apt:
      name: 
        - "{{ apache_package }}" 
        - "{{ lib_php_package }}" 
      state: latest
    when: ansible_distribution == "Ubuntu"
                                           

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Rocky)
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install mariadb package (Ubuntu)
    apt: 
      name: mariadb
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest



